### ISSUE TITLE
AEM 6.5.5 Multifeild with dropdown creating extra items at the node

### ISSUE THREAD

**Issue by NagalaxmiT** [arunpatidar02/aem63app-repo#5] opened 2021-05-31 06:51 UTC
Hi Arun,

I am using a multifiled with dropdown selection to populate feilds based on the selection, I have added the js which is suggested [here](https://experienceleaguecommunities.adobe.com/t5/adobe-experience-manager/aem6-4-multifield-with-show-hide-dropdown-changing-all-the-items/qaq-p/237275/comment-id/39523#M39523
[videoList-0.1.zip](https://github.com/arunpatidar02/aem63app-repo/files/6568322/videoList-0.1.zip)
), now the dialog is retaining the values but at the node level its adding an extra empty node. When I try to add another item to the existing list its adding the entire set double time.  I have attached the complete component below in the AEM package but when I try to author the component its adding an empty item for each filed. Pls see the below attachment. 
![image](https://user-images.githubusercontent.com/85091227/120151797-55cea680-c20a-11eb-8ae6-6848959eb316.png)

**Comment by arunpatidar02** [comment] 2021-05-31 09:41
@NagalaxmiT The javascript used to show hide multifield does not do any modification.
Could you please try to disable this javascript and check the dialog value again?
I am sure there is another javascript that is causing the issue.

**Comment by NagalaxmiT** [comment] 2021-05-31 11:40
@arunpatidar02 
After I disable the java script the dropdown options are not populating at the dialogue though I have selected the option. instead of using cq-dialog-dropdown-showhide-multi, when I use the cq-dialog-dropdown-showhide the values are storing successfully at the node level with out empty, but when I try to re-open the dialog the authored values are disappearing. I am new to listerns unable to identify where it is going wrong.

**Comment by arunpatidar02** [comment] 2021-05-31 18:39
@NagalaxmiT  could you please share your dialog xml?

**Comment by NagalaxmiT** [comment] 2021-06-01 08:57
@arunpatidar02 , pls find the attached xml in zip format
[.content.xml.zip](https://github.com/arunpatidar02/aem63app-repo/files/6574931/default.content.xml.zip)

**Comment by arunpatidar02** [comment] 2021-06-01 16:36
@NagalaxmiT 
The issue is with your dialog, you have 2 filed with same name e.g. `./vidpath `in `dmvideo` and `ytvideo` node.
Multifield try to get all the values and from name field and save it doesn't matter if values are hidden or shown. You need to disabled the item values, just write a custom script to disable all field for hidden elements, this will fix your issue.

The issue is not due to showhide but due to dialog structure. Closing the bug now.

**Closed as completed by arunpatidar02** 2021-06-01 16:36 UTC
